version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=catalogosites
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
